### ISSUE TITLE
Support Subqueries

### ISSUE THREAD

**Issue by Wizek** [rails/arel#150]
I'm redirected here from ernie/squeel#187

Currently it seems we only have support for IN type of subqueries, like

``` sql
SELECT 'users'.* FROM 'users' WHERE 'users'.'id' IN (SELECT max('users'.'id') FROM 'users')
```

It would be nice if we could write something like:

``` sql
SELECT 'users'.* FROM 'users' WHERE 'users'.'id' < (SELECT max('users'.'id') FROM 'users')
```

This example is very simplistic and not overly useful at this complexity level, and only came up with it so that I could easily demonstrate the issue I (and others, please see ernie/squeel#187) were having.

Furthermore, it would be all the best if by this improvement we could generate subquery-based single SQL statement wherever it is supported (not restricted to `WHERE` clause but also in `SELECT`, `FROM`, etc...)

**Comment by filipegiusti** [comment]
@dmitry thanks, that hack works.

I'm trying to use subqueries for getting the down votes that happened after the last up vote. I couldn't find a different way to do it in sql and arel doesn't support it without a hack.

The code below produces a string with `!ruby/object` on it.

```ruby
feedback = Feedback.arel_table
subquery = Feedback.select(feedback[:created_at].maximum).where(vote: :up)
Feedback
  .where(vote: :down)
  .where(feedback[:created_at].gt(subquery)).to_sql
```

@dcunited001 do you still think arel shouldn't support it?

**Comment by dmitry** [comment]
`Arel.sql("(#{subquery})")` should fix that.

**Comment by kbrock** [comment]
One issue is your `subquery` which is created with `Feedback.select().where()` uses a string builder. So the bind values are lost. Then when the time comes to build `Feedback.where().where(subquery)`, it builds bind variables for just the main query, and the bind variables associated with `subquery` are not added.

This logic is found in associations.

Think the main problem here is with rails not arel.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
