### ISSUE TITLE
Do we need set mysql function alias by default

### ISSUE THREAD

**Issue by timsly** [rails/arel#154]
I tried to build complex query using arel(add `sum` into `having`)
But due to [default aliases](https://github.com/rails/arel/blob/v3.0.2/lib/arel/expressions.rb) i couldn't make it
So i had to use smth like

```
condition = arel_table[:time].sum
condition.alias = nil

scoped
  having(condition.gteq(1000)).
  group(:user_id)
```

Also i couldn't pass `nil` or `false` to `as` method, because it try to build  SqlLiteral object, see [here](https://github.com/rails/arel/blob/v3.0.2/lib/arel/nodes/function.rb#L15)

I thought that we can allow `nil` as `as`  param, but also we can remove those default aliases(of course if it's not break smth) and set alias explicitly

**Comment by amalagaura** [comment]
This also broke an attempt at using a window function for me. I needed to do:
```
Arel.sql('sum(count(*)) over (order by min_timestamp) as count')
```
 instead of:

```
window = Arel::Nodes::Window.new.order(:min_commented_time)
min_arrivals_cte['count(*)'].sum.over(window)). # Tried in Arel, but doesn't work, introduces an alias
```
`min_arrivals_cte['*'].count.sum.over(window)` also does not work, but I am not sure if it should.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
