### ISSUE TITLE
Add support for sql comments

### ISSUE THREAD

**Issue by grosser** [rails/arel#156]
It would be great to be able to annotate sql with comments to tell where a query came from/or user/account runs it -> visible in slow query log and mysql status

```
User.where(xxx).comment("user.rb:11")
-> SELECT * FROM users WHERE xxx /* user.rb:11 */


User.where(xxx).comment("doing slow stuff in the console: do not kill")
```

**Comment by hlascelles** [comment]
Marginalia's functionality is (largely) now in Rails, so not needed. You can use:

```ruby
          config.active_record.query_log_tags_enabled = true
          config.active_record.query_log_tags = [
            :application,
            :controller,
            :action,
            {
              foo: -> { Time.current }, # Dynamic value
            }
          ]
```

However... one thing it doesn't do is what the original comment was suggesting. A simple AREL to add `.comment` on a query. You can use marginalia to wrap a code block, but that could change to spawn multiple queries.

I think we still need  `.comment` feature.
