### ISSUE TITLE
Sql Union in postgresql

### ISSUE THREAD

**Issue by kainlite** [rails/arel#158]
The parentheses for the union seems to be poking on postgresql, on postgresql is not working at least on version 9.1, if I add the parentheses in the ToSql visitor, I can use the union without issues..

``` ruby
      def visit_Arel_Nodes_Union o
        "( #{visit o.left} ) UNION ( #{visit o.right} )"
      end

      def visit_Arel_Nodes_UnionAll o
        "( #{visit o.left} ) UNION ALL ( #{visit o.right} )"
      end
```

I've seen this old issue: [Issue 58](https://github.com/rails/arel/issues/58), but that should not be managed by the specific visitor for mysql or postgres in my case?

Example:

``` ruby
a = User.where(id: 1)
b = User.where(id: 2)

union = Arel::Nodes::Union.new( a.ast, b.ast )

User.find_by_sql( union.to_sql )
```

Mysql likes:

``` sql
( SELECT "users".* FROM "users" WHERE "users"."id" = 1 UNION SELECT "users".* FROM "users" WHERE "users"."id" = 2 )
```

But postgresql complains about the sintax:
ActiveRecord::StatementInvalid: PG::Error: ERROR:  syntax error at or near "UNION"
LINE 1: ...HERE "users"."id" = 1 ORDER BY users.lastname ASC UNION SELE...

Postgresql likes:

``` sql
( SELECT "users".* FROM "users" WHERE "users"."id" = 1 ) UNION ( SELECT "users".* FROM "users" WHERE "users"."id" = 2 )
```

Let me know how can I help to get this right :smile:

**Comment by kbrock** [comment]
Fix has been applied to Rails
