### ISSUE TITLE
Implement case statement

### ISSUE THREAD

**Issue by pschambacher** [rails/arel#168]
Just discovered (because I actually needed it) the SQL CASE statement.
I've had a look but it seems ARel does not handle it ?

Here are some links on this statement:
 - http://naspinski.net/post/Ternary-Operator-in-SQL.aspx
 - http://stackoverflow.com/questions/5487892/sql-server-case-when-or-then-else-end-the-or-is-not-supported

Low priority even for myself. Just reporting it :smile:

**Comment by fusion2004** [comment]
@felixbuenemann Still considering working that gist into a PR? I'm definitely still interested.

**Comment by felixbuenemann** [comment]
@fusion2004 I kinda forgot about this. I'll see if I can come up with a PR. I'm pretty busy with other projects ATM, so it could be a week or two until I get around to it.

**Comment by felixbuenemann** [comment]
@fusion2004 Sorry for the delay, you can try it out using:
```ruby
gem "arel", github: "felixbuenemann/arel", branch: "case-node"
```
You also need rails master, if working with rails (due to the arel version constraint).

**Comment by ahcarpenter** [comment]
@danieljacobarcher, had most def not considered as to whether there had been case statements in arel prior to having read your post--thanks for the inspiration my good sir!
