### ISSUE TITLE
not_in with an empty array produces no results

### ISSUE THREAD

**Issue by zephyr-dev** [rails/arel#175]
Doing 

``` ruby
User.where(User.arel_table[:id].not_in([]))
```

performs the query 

``` sql
SELECT "users".* FROM "users" WHERE ("users"."id" NOT IN (NULL))
```

which produces an empty result set. This seems a little strange, both from the SQL semantics of `NOT IN (NULL)` not matching anything, and from Arel. From the usual use case, I would expect `not_in([])` to match all records.

**Comment by scifisamurai** [comment]
For anyone else coming across this, it looks like this issue has been fixed.  When I ran the arel statement above in Rails 3.2.18 the SQL generated did not have this issue.

**Comment by townegr** [comment]
In Rails 5.2, I see a similar scenario when explicitly excluding `nil`:
```ruby
User.where(User.arel_table[:id].not_in([nil]))
```
Zero results are returned from the query.
