### ISSUE TITLE
Error with Arel visitors and has_and_belongs_to_many

### ISSUE THREAD

**Issue by icambron** [rails/arel#220]
I'm not sure if this is a bug in Arel, in Rails, or in me, but this seemed like the sanest place to post it, so here goes.

Let's say I have an Arel visitee like [this one](https://github.com/dockyard/postgres_ext/blob/master/lib/postgres_ext/arel/visitors/to_sql.rb). The idea is that it checks some properties on the column and acts accordingly:

``` rb
module Arel
  module Visitors
    class ToSql
      def visit_Array o, a
        column = a.relation.engine.columns.find { |col| col.name == a.name.to_s } if a
        #do some column stuff
    end
  end
end
```

And let's say you have a relation like this:

``` rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :colleges
```

When you do something like this, you get an error:

``` rb
@college = College.find(params[:college_id])
@student.colleges.destroy(@college)
```

```
NoMethodError - undefined method `abstract_class?' for Object:Class:
  activerecord (4.0.1) lib/active_record/model_schema.rb:139:in `reset_table_name'
  activerecord (4.0.1) lib/active_record/model_schema.rb:103:in `table_name'
  activerecord (4.0.1) lib/active_record/model_schema.rb:208:in `columns'
  /Users/isaac/code/postgres_ext/lib/postgres_ext/arel/visitors/to_sql.rb:12:in `visit_Array'
```

My I-don't-actually-know-what-I'm-talking-about analysis is that Arel passes an Arel struct to the visitee, which calls `ModelSchema#columns` on its `engine` property, which in turn ends up calling `ModelSchema#reset_table_name`. The problem is that the Arel struct looks like this:

```
#<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fea685f12e8 @name="colleges_students", @engine=ActiveRecord::Base, @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name="college_id">
```

Specifically, the `engine` property is set to an instance of `ActiveRecord::Base`. But `reset_table_name` seems to [expect that engine is a subclass](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/model_schema.rb#L142) of `ActiveRecord::Base`:

``` rb
 elsif superclass.abstract_class?
```

Which causes kerplosions, because the superclass is really just `Object:Class`. I think.

Since I have no broad understanding of how this is supposed to work, I don't know if a) Arel is not supposed to be providing an `ActiveRecord::Base` here or b) Rails should be expecting one or c) there is something terribly wrong with the visitation code.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
