### ISSUE TITLE
1000 records limit on databases

### ISSUE THREAD

**Issue by westlakem** [rails/arel#297]
Sometimes when eager loading, I get more then 1000 records back, which cause an IN clause overload.

What I am recommending is have an interceptor grab the array of items that will be going into the "IN" clause, and if size > 1000, then generate the following clause:

AND (codes IN (...first 1000 codes...)
OR codes IN (...second 1000 codes...)

OR codes IN (... etc, etc, etc, until last codes entered))

The code could be written as the following, I'm just not sure where to put it.

if codes.size > 1 && codes.size <= 1000
# perform in query

else if codes.size > 1000
while codes.size > 1000 do
in_clause << "OR TABLE.CODES IN (#{codes.pop[1000]})"
end
in_clause << "OR TABLE.CODES IN (#{codes})"
end

**Comment by wconrad** [comment]
I ended up investigating this as well, before I found this issue.

Here's a [gist to reproduce the issue](https://gist.github.com/wconrad/583aa946e283385c480b)

And here is my clumsy attempt to fix it: https://github.com/wconrad/arel/commit/ccfc85972f2b3f77086137d8ca900e060be19f3a .  It takes a blunt instrument to the AST, breaking apart big where statements where it finds them.  It only does that for Oracle.

**Comment by r4v5** [comment]
Note that there is a practical limit to how many IDs you can select by chaining ID IN (). I can say from experience that the limit to ```SELECT * FROM table WHERE INDEXED_COLUMN = number AND ID NOT IN () AND ID NOT IN()``` chaining before Oracle simply chokes and your DBA gets paged is less than 90,000.

**Comment by wconrad** [comment]
@r4v5 That's good to know.  The good solution for large numbers of value is probably to write the values to a temporary table and use it in a join.

**Comment by r4v5** [comment]
Yep, that's the solution we ended up using. I don't know if it'd be possible, let alone easy, to do automatically through Arel.

**Comment by westlakem** [comment]
I modified the to_sql.rb file to separate them into 999 record chunks with an "OR" statement inbetween them 

     On Saturday, February 21, 2015 12:08 PM, Mason Donahue <notifications@github.com> wrote:
   

 Yep, that's the solution we ended up using. I don't know if it'd be possible, let alone easy, to do automatically through Arel.—

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
