### ISSUE TITLE
Database links

### ISSUE THREAD

**Issue by westlakem** [rails/arel#298]
I am trying to use database links, and need to be able to drop the link names during the "where"/"on" clauses and not sure where else.

Currently the sql runs:

select T1.\* from T2@DB2 where T2@DB2.column = 42

which won't work because of the "where T2@DB2.column".  I have created a fix for this, but I'm not sure where all I have to put it, or if there is a better place to put it.

Both changes are made in the \visitors\to_sql.rb file

One fix is to the "wheres" section in "visit_Arel_Nodes_SelectCore o,a" changing that section from:

```
    unless o.wheres.empty?
      str << WHERE
      len = o.wheres.length - 1
      o.wheres.each_with_index do |x, i|
        str << visit(y, a)
        str << AND unless len == i
      end
    end
```

to 

```
    unless o.wheres.empty?
      str << WHERE
      len = o.wheres.length - 1
      o.wheres.each_with_index do |x, i|
        y = x.clone
        y.instance_variable_get(:@children).each do |node|
          if node.instance_variable_get(:@left)
            node.instance_variable_get(:@left).relation.instance_variable_set(:@name, node.instance_variable_get(:@left).relation.instance_variable_get(:@name).gsub(/\@(.*)/,''))
          end
        end
        str << visit(y, a)
        str << AND unless len == i
      end
    end
```

and the other is changing changing:

```
  def visit_Arel_Nodes_On o, a
    "ON #{visit o.expr, a}"
  end
```

to

```
  def visit_Arel_Nodes_On o, a
    object_expression = o.expr.clone
    object_expression.left.relation.instance_variable_set(:@name, o.expr.left.relation.instance_variable_get(:@name).gsub(/\@(.*)/,''))
    "ON #{visit object_expression, a}"
  end
```

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
