### ISSUE TITLE
 NoMethodError: undefined method `val' for "$1":Arel::Nodes::BindParam

### ISSUE THREAD

**Issue by Bazley** [rails/arel#345]
I apologise if this is not the right place to mention this, but I can't find any info about this anywhere else. I think it's an arel problem but I'm by no means an expert.
I'm getting this error:

NoMethodError: undefined method `val' for "$1":Arel::Nodes::BindParam

Has this error been documented before?

The error is caused by this line in user.rb:
    self.create_character unless character

test/models/character_test.rb:
    require 'test_helper'
    class CharacterTest < ActiveSupport::TestCase
      def setup
        @user = User.new(name: "Example User", email: "user@example.com", callsign: "example",
                         password: "foobar", password_confirmation: "foobar")
        @user.save
        @character = @user.character
      end
      test "character should be valid" do
        assert @character.valid?
      end
    end # CharacterTest

In the gemfile:
gem 'arel', '6.0.0.beta2'
(get the same error message with version 6.0.0)

character.rb:
class Character < ActiveRecord::Base
  belongs_to :sociable, polymorphic: true
end

user.rb:
class User < ActiveRecord::Base
  has_one  :character, as: :sociable
  before_validation do
    self.create_character unless character
  end
  .
  .
end

(Posted on Stackoverflow here: http://stackoverflow.com/questions/27671756/rails-arel-unit-test-error)

**Comment by bog306** [comment]
Thanks!

**Comment by xEasy** [comment]
Good Job! :+1:
