### ISSUE TITLE
Regression: order with lower or another NamedFunction

### ISSUE THREAD

**Issue by luckynumberslevin** [rails/arel#347]
With 5.0.1.20140414130214 version I did this:
```ruby
Order.order(Order.arel_table[:lastname].lower.desc)
# => SELECT "orders".* FROM "orders"  ORDER BY LOWER("orders"."title") DESC
```
As you can see it works well.

Since 6.0.0, I had this error for the same call 
```ruby
Order.order(Order.arel_table[:title].lower.desc)
# => undefined method `desc' for #<Arel::Nodes::NamedFunction:0x007fa172f54d88>
```

If I try these calls there is no problem:
```ruby
Order.order(Order.arel_table[:title].desc)
# => SELECT "orders".* FROM "orders"  ORDER BY "orders"."title" DESC
Order.order(Order.arel_table[:title].lower)
# => SELECT "orders".* FROM "orders"  ORDER BY LOWER("orders"."title")
```

So, is there another method to aggregate descending sort with a NamedFunction as lower with the new version? Or is it a regression?

**Comment by rafaelfranca** [comment]
This is not a regression, it was done by design. These methods were deprecated in a `Function` node, so they were removed at 6.0 release. This is one of the reason that we bump a major release.

**Comment by luckynumberslevin** [comment]
Well, understood. 

However, I don't find any doc or source to solve my problem. Do you have an example to do a descending sort with a NamedFunction with the new design?

**Comment by rafaelfranca** [comment]
See the implementation https://github.com/rails/arel/blob/5-0-stable/lib/arel/order_predications.rb#L8. Just create a new node

**Comment by luckynumberslevin** [comment]
Ok I got it, 
Thank you for your help!

If somebody has the same problem, here my solution:
```ruby 
Order.order(Arel::Nodes::Descending.new Order.arel_table[:title].lower)
# => SELECT "orders".* FROM "orders"  ORDER BY LOWER("orders"."title") DESC
```
