### ISSUE TITLE
Trouble with SelectManager#to_a deprecation/removal

### ISSUE THREAD

**Issue by nazgob** [rails/arel#353]
Hello! I have issues with change introduced in this commit https://github.com/rails/arel/commit/d956772b3c61d97940ebcccd7c83e2397ca0c36c

I'm doing something like this using deprecated `SelectManager#to_a`. How can I achieve similar result without it?

```ruby
contacts = Arel::Table.new("contacts", db_config)
contacts.project(Arel.star.count.as('count')).to_a
=> [#<struct Arel::SelectManager::Row data={"count"=>42}>]
```
Is this how it should be done now?

```ruby
contacts = Arel::Table.new("#{crm_db_name}.contacts", crm_db)
sql = contacts.project(Arel.star.count.as('count')).to_sql
contacts.engine.connection.execute(sql).each {|row| row}
```

Thanks!

**Comment by hkairi** [comment]
Hello

I was facing the warning message and i decided to do the following : 

```ruby
contacts = Arel::Table.new("#{crm_db_name}.contacts", crm_db)
sql = contacts.project(Arel.star.count.as('count')).to_sql
contacts.engine.connection.execute(sql).map {|row| row}
```

I don't know if there is a better way  :(

**Comment by rafaelfranca** [comment]
Yeah, this is the way you should implement it now.
