### ISSUE TITLE
Arel::Nodes::Function#not_eq with nil outputing "!= NULL"

### ISSUE THREAD

**Issue by bbenezech** [rails/arel#354]
```ruby
Arel::Nodes::NotEqual.new(Arel::Nodes::NamedFunction.new('COALESCE', [quoted(true)]),nil).to_sql
```

```sql
COALESCE(1) IS NOT NULL
```

Looks good.

```ruby
# the same thing explicitly
Arel::Nodes::NamedFunction.new('COALESCE', [quoted(true)]).not_eq(nil).to_sql
```

```sql
COALESCE(1) != NULL
```

Does not look good.

Is this a bug ?

With Arel version `=== 6.0.0 / 2014-11-25`

Thanks for all the awesomeness, sorry if I'm wasting any of your valuable time on fixed/pointless stuff.

**Comment by sgrif** [comment]
Yes, this is fixed in Arel 7.

**Comment by sgrif** [comment]
https://github.com/rails/arel/commit/ba5effdc59f27bcd71f51a514a5496448bfad52c

**Comment by benjaminwood** [comment]
For anybody else that stumbles upon this... you'll also want to consider: https://github.com/rails/arel/commit/0cd5fa9671592a16ee34f0718704b15f27911620 :smile:

Thanks for the fix @sgrif.
