### ISSUE TITLE
Is it possible to use Arel without ActiveRecord?

### ISSUE THREAD

**Issue by tuzz** [rails/arel#373]
I'd like to write a rack app that uses arel and is backed by a mysql database. Is it possible to do this without using activerecord? I noticed you can set the `Arel::Table.engine`, but I wasn't sure what to set this to.

**Comment by rafaelfranca** [comment]
To something that implements the Active Record API that Arel needs. Also, please don't ask questions in the issue tracker. Use the Rails Core mailing list

**Comment by tuzz** [comment]
Ok, thanks.
