### ISSUE TITLE
Version 6.0.1 causes error: `method_missing': undefined method `active_record'

### ISSUE THREAD

**Issue by heinencreative** [rails/arel#375]
Noticed this issue when running a bundle update this morning on a rails 4.2.0 project. Reverting back to version 6.0.0 fixes the error. http://stackoverflow.com/questions/31354785/rails-4-2-3-method-missing-undefined-method-active-record/

**Comment by rafaelfranca** [comment]
Thank you. There is no way of this version of arel cause an error like this. See the diff https://github.com/rails/arel/compare/v6.0.0...v6.0.1. Looks like there is something else causing it.

**Comment by rafaelfranca** [comment]
Ok. I know what happened. It is a permission problem. Releasing 6.0.2

**Comment by heinencreative** [comment]
That did the trick, thanks!
