### ISSUE TITLE
Is 3.x support deprecated?

### ISSUE THREAD

**Issue by beedub** [rails/arel#380]
I had a couple of PR's set against 3-0-stable a while back and they were closed in favor of merging to arel master instead, which never made it to 3-0. I also have an open PR against 3-0-stable that has been open forever.

PRs in question:

https://github.com/rails/arel/pull/188
https://github.com/rails/arel/pull/180
https://github.com/rails/arel/pull/179

**Comment by rafaelfranca** [comment]
Yes. It is deprecated. Arel 3.x is for Rails 3.x that is already deprecated for almost two years.
