### ISSUE TITLE
Lateral Join ?

### ISSUE THREAD

**Issue by gdurelle** [rails/arel#382]
Just wondering if it's possible to perform a LATERAL JOIN with Arel ?
Or is this something to implement ? (and if not why :p)

**Comment by saturnflyer** [comment]
I'm interested in this too @gdurelle. I don't think Arel currently supports it as is, but I don't know for sure. I'll try to post details here if I figure anything out

**Comment by mabeller** [comment]
+1

**Comment by spscream** [comment]
+1

**Comment by woto** [comment]
:( http://docs.sqlalchemy.org/en/latest/core/tutorial.html#lateral-selects

**Comment by claudiug** [comment]
I guess sequel: http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-lateral
