### ISSUE TITLE
Rakefile and test suite not included in released gem archives

### ISSUE THREAD

**Issue by davexunit** [rails/arel#384]
This prevents one from independently verifying that the official gem release passes its own test suite.

**Comment by rafaelfranca** [comment]
Yes, it is by design. Rubygems' `test_files` is deprecated and also we think If you want to verify that gem release passes its own test suite just look the tagged verrsion build in our continuos integration test suite.

**Comment by davexunit** [comment]
I believe you are forgetting an important use-case: alternative package managers.  I am trying to package Arel for a GNU/Linux distribution, and part of the build process is to run the tests to make sure the build works with the rest of the system's dependencies.  I have packaged many other gems that include the Rakefile and test suite and I've been able to verify that the gems work in *my* continuous integration system in which the complete dependency graph is verified, all the way down to libc.

I've also gone the route of building from the release tarballs hosted here on GitHub, but they are just an auto-generated tarball for a tag, not the releases that people are actually using and they typically present other issues.  If you really do not want to include the test suite in released gems, I suppose that I will have to make do with the tarball.

**Comment by rekado** [comment]
I'd like to express support for the request to include tests in gem releases.

**Comment by rafaelfranca** [comment]
We plan to send to Rubygems just the files that are needed to run the gem. Tests are not going to be released. They will just increase the size of the package and users don't need those files.

See https://github.com/rubygems/rubygems/commit/c07356a2de3576bfc5c11192db99a01037524015 and https://github.com/rubygems/guides/issues/90.

**Comment by davexunit** [comment]
This is very disappointing.  PyPI, the RubyGems equivalent for Python, hosts releases complete with full test suites.  I'm unsure why the convention here and elsewhere in the Ruby community is to exclude tests from releases such that downstream users/packagers cannot verify that the package integrates with their system.

Thanks for the relevant links.
