### ISSUE TITLE
Cannot use infix operations in UpdateManager

### ISSUE THREAD

**Issue by drbawb** [rails/arel#393]
Suppose you would like to write a query such as:

`UPDATE "accounts" SET balance = balance - 1`

Where the RHS of the assignment is an infix operation. I thought that writing such a query in Arel might look like this:

```
accounts = [some table]
um       = [some update manager]

um.table(accounts)
  .set(accounts[:balance] => (accounts[:balance] - 1).expr)
  .to_sql
```

Presently [#visit_Arel_Nodes_Assignment](https://github.com/rails/arel/blob/935796f4fd7d75950db87156d6540028a9044fdf/lib/arel/visitors/to_sql.rb#L660) falls through and attempts to quote the RHS of the assignment (which in this case would be `Nodes::Subtraction` and less specifically a `Nodes::InfixOperation`.)

So, assuming `accounts[:balance]` is a numeric type, when such an expression is visited w/ `#to_sql` this actually yields:

```
UPDATE "accounts" SET balance = NULL
```

The result was a bit surprising, to say the least.  
_(NOTE: this was tested w/ the `pg` adapter. )_

This can be worked around this by wrapping the infix operation in a SqlLiteral, but in my experience that leads to messy _and potentially error-prone_ code.

---

In my limited testing, if something like the following case were added:

```
when Arel::Nodes::InfixOperation
  collector = visit o.left, collector
  collector << " = "
  visit o.right.left, collector
  collector << " #{o.right.operator.to_s} "
  visit o.right.right, collector
```

`#to_sql` would then yield the expected expression (though this particular implementation leaves the _LHS of the infix expression_ as a fully qualified field, which may not be desirable.)

```
UPDATE "accounts" SET "balance" = "accounts"."balance" - 1
```

---

As I see it there are two distinct issues here:
1. I find the assignment to NULL to be both surprising and incorrect. If the RHS of the assignment cannot be visited appropriately then _(in my opinion)_ it should not be allowed to produce SQL which will erase a field.
2. It would be _great_ to have real support for visiting infix expressions in assignments. As you can see above I believe a patch is workable; however I'm not sure I know enough about the internals of Arel to submit a proper one.

**Comment by PedroSena** [comment]
Hey @drbawb can you please take a look at https://github.com/rails/arel/pull/477 and make sure it matches what you are expecting ? Apparently simply adding Arel::Nodes::InfixOperation to https://github.com/rails/arel/blob/935796f4fd7d75950db87156d6540028a9044fdf/lib/arel/visitors/to_sql.rb#L662 does the trick.

Thanks

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
