### ISSUE TITLE
NamedFunction cannot be used for ordering anymore in arel 6

### ISSUE THREAD

**Issue by fschwahn** [rails/arel#399]
Hi,
with arel 5 I could do the following:

```ruby
t = Arel::Table.new(:table)
Arel::Nodes::NamedFunction.new('CAST', [t[:date].as("TIME")]).desc
```

Which would allow me to order according to a named function. This does not work in arel 6 anymore:

    undefined method `asc' for #<Arel::Nodes::NamedFunction:0x007fc858b977d8> (NoMethodError)

Is there any reason this functionality was removed, or is this a regression?

The following can be used to reproduce:
```ruby
#!/usr/bin/env ruby

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'sqlite3'

  # Arel 6
  gem 'activerecord', '~> 4.2', require: 'active_record'
  gem 'arel', '~> 6.0'

  # Arel 5
  # gem 'activerecord', '~> 4.1', require: 'active_record'
  # gem 'arel', '~> 5.0'
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

t = Arel::Table.new(:table, ActiveRecord::Base)
puts Arel::Nodes::NamedFunction.new('CAST', [t[:date].as("TIME")]).desc.to_sql
```

All the best,
Fabian

**Comment by vipulnsward** [comment]
Looks like a regression.
`Arel::Expression` was deprecated and removed. The `desc`, `asc` calls were being imported from `Arel::OrderPredications` into `Arel::Expression` and later to `NamedFunction`.

You can import `OrderPredications` manually though. I don't think there's a need to import in in `NamedFunction` right now.

**Comment by fschwahn** [comment]
@vipulnsward Thank you for your answer, I manually imported `Arel::OrderPredications` into `Arel::Nodes::NamedFunction` and it works perfectly.

I'm not sure if this issue should be closed, as it seems to be a regression. Maybe documenting it somewhere would be enough?

**Comment by carsonreinke** [comment]
Fix here https://github.com/rails/arel/pull/381
