### ISSUE TITLE
seeking assistance regarding construction of complex sql queries using arel

### ISSUE THREAD

**Issue by trekr5** [rails/arel#401]
Hi,

I have a complex SQL query that I'm attempting to run in a ruby script.

I have attempted to run the raw SQL within the script using ActiveRecord. It works for really basic queries but not for complex SQL queries which doesn't suit my purpose.

My next approach would be generate ActiveRecord schemas of the tables (and fields) in question and then use ActiveRecord to perform these complex SQL actions (like join, case , group).

Would the gem arel be able to help me with this?

Assistance appreciated.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
