### ISSUE TITLE
between broken with decimal columns

### ISSUE THREAD

**Issue by ioquatix** [rails/arel#411]
If you try to supply a range made from `BigDecimal` values (e.g. provided by columns of type decimal), the code breaks.

https://github.com/rails/arel/blob/63ea665c8083f8069a0d05d4f15cf19e08e470a6/lib/arel/predications.rb#L27-L45

It's because you can't compare BigDecimal with INFINITY

```ruby
> BigDecimal.new(10) == Float::INFINITY                           
FloatDomainError: Infinity
from (pry):10:in `to_r'
```

The solution is not to use comparison but to use Float#infinite? and BigDecimal#infinite?

```
[13] pry(main)> Float::INFINITY.infinite?                                       
=> 1
[14] pry(main)> -Float::INFINITY.infinite?                                      
=> -1
[15] pry(main)> BigDecimal::INFINITY.infinite?                                  
=> 1
[16] pry(main)> -BigDecimal::INFINITY.infinite?                                 
=> -1
```

The problem this introduces is that it no longer works for Numeric values, e.g. `Fixnum` and `Bignum`. However, these can never be infinite.

**Comment by ioquatix** [comment]
I have filed a bug report because it might make sense for Numeric to provide #infinite?

https://bugs.ruby-lang.org/issues/12039

Not sure what the best outcome is here, but I don't think this should fail.

**Comment by sgrif** [comment]
Currently, the rough plan is to remove the infinite handling from Arel, and move it into Active Record as a result of https://github.com/rails/rails/commit/6efb39456a8ee3569f3787cc2f26c041365a0e27. Your proposed fix in Ruby would solve this, and is probably the best place to handle it.

**Comment by ioquatix** [comment]
Thanks for the quick reply.

What is the reasoning behind moving it to the ActiveRecord code base?

**Comment by sgrif** [comment]
Arel is an AST, not a query builder. We need information that only exists at the AR level for this to be useful.

**Comment by ioquatix** [comment]
@sgrif Just thought I'd let you know, that this is now fixed in Ruby.

**Comment by sgrif** [comment]
Thank you for following up.

**Comment by ioquatix** [comment]
@sgrif Thanks so much for all your hard work dude, you're awesome!
