### ISSUE TITLE
Multiple CTE in single query

### ISSUE THREAD

**Issue by axvm** [rails/arel#413]
Hi,

I'd like to know is it possible to combine multiple CTE in single query? I am looking for way to get result like this:

```SQL
WITH 'cte1' AS (
...
),
WITH RECURSIVE 'cte2' AS (
...
),
WITH 'cte3' AS (
...
)
SELECT ... FROM 'cte3' WHERE ...
```

Thanks.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by midhunkrishna** [comment]
for anyone who comes here, https://gist.github.com/midhunkrishna/2adc07cd77002b5d49358ef69237b805
