### ISSUE TITLE
Should Arel::Nodes::True.new() be 1 in sqlite3?

### ISSUE THREAD

**Issue by oddg** [rails/arel#415]
I am using `Arel::Nodes::True.new()` as a fallback for a query construction. It works fine in development with the postgresql adapter but it breaks my tests as they are using the sqlite3 adapter. I figured out that this is because sqlite3 takes `1` instead of `true`:

    $ rails console test
    Running via Spring preloader in process 8777
    Loading test environment (Rails 4.1.6)
    2.2.3 :001 > Mymodel.where(1).count
     => 0 
    2.2.3 :002 > Mymodel.where(Arel::Nodes::True.new()).count
    SQLite3::SQLException: no such column: TRUE: SELECT COUNT(*) FROM "mymodels"  WHERE (TRUE)

I can fix the issue by checking the environment and returning either `Arel::Nodes::True.new()` or `1` but it does not feel right.

**Comment by tlkahn** [comment]
I made some changes on sqlite.rb, so that `Arel::Nodes::True.new().to_sql == '1'` and  `Arel::Nodes::False.new().to_sql == '0'`. I have sent the pull request at: https://github.com/rails/arel/pull/417
