### ISSUE TITLE
Expecting #count to return COUNT() instead of INT value

### ISSUE THREAD

**Issue by spodlecki** [rails/arel#423]
Gem version(s)
- arel (6.0.3)
- rails (4.2.5.1)

I'm attempting to build a query (MySQL) with Arel on Rails 4, that matches the following:

```
SELECT posts.* FROM posts LEFT JOIN categories_posts ON posts.id = categories_posts.post_id GROUP BY post_id HAVING COUNT(DISTINCT categories_posts.category_id) = COUNT(DISTINCT categories_posts.category_id <> 10);
```

The join process and general query works great, until the `HAVING COUNT` -- it's possible I'm doing this wrong or making some invalid assumptions, but I even tried it on Scuttle and it was doing the same thing.

Here is Scuttle's output (I'm passing `true` to the count methods so it becomes `DISTINCT`:

```
Post.select(Post.arel_table[Arel.star]).having(
  CategoriesPost.arel_table[:category_id].count(true).eq(
    CategoriesPost.arel_table[:category_id].not_eq(10).count(true)
  )
).joins(
  Post.arel_table.join(CategoriesPost.arel_table).on(
    Post.arel_table[:id].eq(CategoriesPost.arel_table[:post_id])
  ).join_sources
).group(:post_id)
```

The goal of this query is to _exclude_ any Post with associated category id of 10. (has many association)...

The final output of the SQL is:

```
SELECT posts.* FROM posts LEFT JOIN categories_posts ON posts.id = categories_posts.post_id GROUP BY post_id HAVING COUNT(DISTINCT categories_posts.category_id) = 0;
```

For some reason, it seems like `#count` is being called as a Ruby method rather than a chained Arel method?? I attempted to build manually by using the Arel::Nodes::Count as well, but was unable to get it going either.

**Comment by spodlecki** [comment]
While Arel still didn't do what I anticipated it to do, I ended up realizing I'm bad at sql. I simply added the category id requirement on an outer join and required the post id to be null.

```
SELECT posts.* FROM posts LEFT OUTER JOIN categories_posts ON posts.id = categories_posts.post_id AND categories_posts.category_id = 10 WHERE categories_posts.post_id IS NULL;
```

**Comment by vipulnsward** [comment]
@spodlecki so this is a still an issue, or can be closed?

**Comment by spodlecki** [comment]
I do still feel its pretty confusing that I couldn't chain `count` so I want to say yes. I'll leave it to you though, @vipulnsward

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
