### ISSUE TITLE
Backporting nil values fixes from master to 6-0-0-stable

### ISSUE THREAD

**Issue by grokse** [rails/arel#436]
Arel 6.0.3
`Post.arel_table[:title].lower.eq(nil).to_sql`
`LOWER("post"."title") = NULL
`
Arel 7:
`Post.arel_table[:title].lower.eq(nil).to_sql`
`LOWER("post"."title") IS NULL`

Cherry picking commits 0b720f7, ba5effd, and 0cd5fa9 seems to resolve it for me.  Would something like this get put onto Arel 6.x so it can work with Rails 4.x?

**Comment by bdmac** [comment]
We just hit this problem as well in a Rails 4.x app. Would love to see this backported to a 6.0.x branch so we can avoid monkey-patching a fix in.

**Comment by rafaelfranca** [comment]
Could you open a PR with it? Thanks
