### ISSUE TITLE
Arel node for an array element (suffix operator)

### ISSUE THREAD

**Issue by printercu** [rails/arel#497]
Hi!

Is there any node for suffix operators to access array elements (postgresql's `integer[]` type) like this:

```ruby
column = Table.arel_table[:column]
low = here_magic_happens(column, '[1]')
Table.where(low.eq nil).or(Table.where(low.gt 5))
# should result in this where clause:
# "table"."column"[1] IS NULL OR "table"."column"[1] > 5
```

Thank you!

**Comment by tenderlove** [comment]
Nope, there isn't.  But if you send a pull request that implements it, we could talk about merging it in! 😀

**Comment by printercu** [comment]
@tenderlove can you please give some advises on this feature. Maybe there is already something very similar in the gem, or some class to inherit, module to include, etc.

Thank you!
