### ISSUE TITLE
Atomic upsert?

### ISSUE THREAD

**Issue by glebm** [rails/arel#520]
A basic upsert has three inputs:

1. Values to insert.
2. Values to update if insertion failed because of a unique index / constraint conflict.
3. Values to return.

All databases supported by Arel support a form upsert:

* On Postgres v9.5+, this is done with [`INSERT ... ON CONFLICT ... DO UPDATE`](https://www.postgresql.org/docs/9.5/static/sql-insert.html).
* On MySQL, this is done with [`INSERT ... ON DUPLICATE KEY UPDATE`](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html). There should only be one unique index on the table that matches the query (https://bugs.mysql.com/bug.php?id=58637).
* SQLite only provides an atomic [`INSERT OR REPLACE`](https://www.sqlite.org/lang_conflict.html) that can be used to implement upsert if the table definition is known, e.g. https://stackoverflow.com/a/7511635/181228. Alternatively, it can be implemented with an `INSERT OR IGNORE`, followed by an `UPDATE`, wrapped in a transaction.
* On Oracle, Microsoft SQL Server, DB2, and Informix, this is done with the [`MERGE ... WHEN [NOT] MATCHED`](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql) syntax (SQL standard).

The lowest common denominator between all these databases is that the conflicting values must belong to a single unique index (there is no way to select them explicitly).

it'd be nice to have a cross-database way to do it (useful for library authors).

Is Arel at the right abstraction level to provide it?

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)

**Comment by mhuggins** [comment]
Where can I find the issue for this in rails/rails?
