### ISSUE TITLE
Registering Visitors

### ISSUE THREAD

**Issue by MariusDanner** [rails/arel#529]
Hi,
I'm trying to use Arel with SAP HANA and I am using [this adapter](https://github.com/SAP/activerecord-hana-adapter). It is using this line to register itself to arel:
`Arel::Visitors::VISITORS['hana'] = Arel::Visitors::Hana` in [this file](https://github.com/SAP/activerecord-hana-adapter/blob/master/lib/arel/visitors/hana.rb)
Unfortunately, you can't register new adapters this way since version 7.0.
Is there any other possibility to register?

Thanks in advance

**Comment by rafaelfranca** [comment]
You don't need to register visitors. You only need to make sure your adapter use the right visitor. See https://github.com/rails/rails/blob/6717d6027ce7f6383baf6c78115debdbcf2348ac/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L812 as example
