### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rodrigoscna** [rails/arel#540]
Hello everyone.

I'm building a [rewrite](https://github.com/sequeljs/ast) of Arel in TypeScript (and later on, a rewrite of ActiveModel and ActiveRecord), and I'd like to know if I can reuse the documentation of [this version](https://github.com/rails/arel/tree/v9.0.0) in my README.md (with proper adaptations).

Thanks in advance!

**Comment by rafaelfranca** [comment]
Yes you can. All code and documentation here is based on the MIT license. You only need to make sure you follow what the MIT license says to do when you derive work.
