### ISSUE TITLE
Can't chain other operators or #as, etc from addition or subtraction

### ISSUE THREAD

**Issue by stevecj** [rails/arel#89]
An addition or subtraction results in a Nodes::Grouping instance, and that class does not have the mixins to support chaining additional methods.  I can't even specify a column name using #as (e.g. (foo_table[:value] + 1).as(foo_plus_one).  Attempting to do so results in...

NoMethodError: undefined method `as' for #Arel::Nodes::Grouping:0x00000102e9b968

Likewise, I can't chain an addition to an addition, etc.  The same problem does not exist for multiplication and division, because those return instances of Nodes::Binary subclasses rather than Nodes::Grouping.

It seems to me that the addition and subtraction operators should return instances of something like a MathGrouping class that includes the same mixins that Nodes::Binary and Attributes::Attribute do (and maybe there should be another module that encapsulates that combination of inclusions).

**Comment by ur5us** [comment]
@parndt Nope, it doesn't work, not even in `arel -v "6.0.0"`.

**Comment by drakmail** [comment]
Same problem :(

**Comment by drakmail** [comment]
Workaround for this case:

```ruby
Arel::Nodes::TableAlias.new(Arel::Nodes::Grouping.new(
  Arel::Nodes::Subtraction.new(
    Arel::Nodes::Subtraction.new(
      items[:quantity],
      items[:available_quantity]
    ),
    items[:to_back_order]
  )
), Arel::Nodes::SqlLiteral.new("AS quantity"))
```

**Comment by ansonhoyt** [comment]
My case is similiar to @drakmail. I wanted to get:
```sql
(activities.logged_at - root_ancestor.logged_at) AS duration
```

I worked around by converting the calculation to SQL and wrapping in `Arel.sql`:

```ruby
# activities = Activity.arel_table
# root_ancestor is an Arel::Table object
...
duration_term = (root_ancestor[:logged_at] - activities[:logged_at]).to_sql
...
@activities.arel
.project(Arel.sql(duration_term).as('duration'))
...
```

**Comment by mbdimitrova** [comment]
Thanks, @drakmail! I extended your solution to match my case in which I have to prioritize operators:

`# (current_revenue - last_month_revenue) / last_month_revenue * 100
 
revenue_change = Arel::Nodes::Grouping.new(
                                 Arel::Nodes::Subtraction.new(
                                   arel_table[:current_revenue],
                                   arel_table[:last_month_revenue]
                                 )
                               )
monthly_revenue_change = Arel::Nodes::TableAlias.new(Arel::Nodes::Grouping.new(
                                               Arel::Nodes::Multiplication.new(
                                                 Arel::Nodes::Division.new(
                                                   revenue_change,
                                                   arel_table[:last_month_revenue]
                                                 ),
                                                100
                                               )
                                             ), Arel::Nodes::SqlLiteral.new('AS monthly_revenue_change'))`

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this issue is still relevant, please consider reopening it over there. (Note that the Rails repository does not accept feature request issues, and requires reproduction steps that rely on Active Record's documented API.)
